//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventorysys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int item_no { get; set; }
        public Nullable<int> Client_id { get; set; }
        public string item_SKU { get; set; }
        public string item_description { get; set; }
        public Nullable<decimal> item_price { get; set; }
        public Nullable<bool> item_Availability { get; set; }
    
        public virtual client client { get; set; }
    }
}
